# Generated by Django 4.0.1 on 2022-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Applied'), (1, 'Interview'), (2, 'WellDone')])),
                ('started_time', models.DateField(editable=False)),
            ],
        ),
    ]
