# Generated by Django 4.0.1 on 2022-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='started_time',
            field=models.DateField(),
        ),
    ]
