# Generated by Django 4.0.1 on 2022-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_intern_started_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='postal',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
