# Generated by Django 4.0.1 on 2022-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_intern_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='status',
            field=models.IntegerField(choices=[(0, 'Applied'), (1, 'Interview'), (2, 'WellDone')], default=0),
        ),
    ]
